# Inspired from https://github.com/neo4j-contrib/neomodel/blob/master/tests-with-docker-compose.sh
version: '3'
services:
  estuary_updater_tests:
    build:
      context: ../
      dockerfile: docker/Dockerfile-tests
    volumes:
      - ../:/src:Z
    links:
      - neo4j
    environment:
      NEO4J_BOLT_URL: bolt://neo4j:neo4j@neo4j:7687
  neo4j:
    image: neo4j:3.3-enterprise
    environment:
      NEO4J_AUTH: none
      NEO4J_dbms_security_procedures_unrestricted: apoc.*
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
